#cloud-config

# set locale
locale: "en_US.UTF-8"

# set timezone
timezone: "Etc/UTC"

ssh_authorized_keys:
${authorized_keys}

${ntp}

zypper:
  repos:
${repositories}
  config:
    gpgCheck: "off"
    solver.onlyRequires: "true"
    download.use_deltarpm: "true"

packages:
  - docker
${packages}
# set hostname
hostname: ${hostname}

runcmd:
${commands}

final_message: "The system is finally up, after $UPTIME seconds"