name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Add debian repository
      uses: myci-actions/add-deb-repo@3
      with:
        repo: http://download.opensuse.org/repositories/systemsmanagement:/terraform/Ubuntu_20.04/
        repo-name: systemsmanagement

    - name: Install libvirt provider for terraform
      run: |
        apt-get update -qq
        apt-get install terraform-provider-libvirt
        
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Validates the Terraform configuration files
    - name: Terraform Validate
      run: terraform validate
